export const CREATE_POST = 'POST/CREATE_POST';
export const FETCH_POSTS = 'POST/FETCH_POSTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

export const FETCH_POSTS_SUCCESS = 'POST/FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'POST/FETCH_POSTS_ERROR';
export const FETCH_POSTS_LOADER = 'POST/FETCH_POSTS_LOADER';

export const FETCH_POST_SUCCESS = 'POST/FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'POST/FETCH_POST_ERROR';
export const FETCH_POST_LOADER = 'POST/FETCH_POST_LOADER';
export const CLEAR_FETCH_POST = 'POST/CLEAR_FETCH_POST';
export const MODAL_SUCCESS = 'APP/MODAL_SUCCESS';
export const MODAL_LOADER = 'APP/MODAL_LOADER';
export const MODAL_ERROR = 'APP/MODAL_ERROR';
